### PR TITLE
Adapt to libxml++ 5.0 and 4.0 too

### PR DESCRIPTION
**Pull request by be1**
This PR includes:
- check for libxml++5.0 and 4.0 in addition to previous checks (3.0 and 2.6)
- set g++ standard to `c++17` because libxml++-5.0 needs this
- refresh configure scripts

This has been tested on:
- Ubuntu 18.04 (Bionic) using libxml++-2.6
- Ubuntu 24.04 (Noble) using libxml++-2.6
- Manjaro latest (as of 2024/12) using libxml++-5.0

Note that libxml++-2.6 uses `std::auto_ptr` which is deprecated since c++11, so warnings appear at compilation time because of the -Wdeprecated-declarations flag.

### CODE REVIEW

**Comment by be1** [comment]
@onkelDead Ok I can remove generated configure files. So I will update the README to indicate that one must use `autoreconf` to generate them before to call configure script.

**Comment by be1** [comment]
Sorry for the incremental pushes. This should be okay now.

**Comment by onkelDead** [comment]
Sorry, but I've a concern regarding commonly change to -std=c++17.

One the one hand I appreciate the support of more recent XML variants.
But I can't live with compiler warnings now raises up due to deprecated auto_ptr. 
Esp. on most recent UbuntuStudio 24.04 (my favorite) which comes by default with XML 2.6,
and I see no hard requirement for an explicit upgrade on it.

My suggestion is to make use of c++17 only if required (depending on availability of libxml++-5.0), 
or enable it with explicit parameter of configure script.

I hope you can agree on it.

**Comment by onkelDead** [comment]
That is weird. I get these warning with your branch (be1:master) as well, even if I patch the Makefile to c++11 and I stuck to figure out the root cause.
Comparing complete cmd-line of  the g++ executions (e.g. OFader.cpp) shows absolute no difference.ö

Sounds strange, but it make a difference, if xml-headers are included like this
`#include <libxml++-2.6/libxml++/libxml++.h>`
or that
`#include <libxml++/libxml++.h>`

Any idea?

**Comment by be1** [comment]
Thanks for your investigation! I can reproduce this strange behavior even with std=c++17: no warning at all!
Would the order of inclusion of headers above make some difference ? I don't know.
In the mean time I can take advantage of this weird behavior and conditionally include <libxml++/libxml++.h> only  if HAVE_XML3 is defined. Would you accept such a patch ?

**Comment by onkelDead** [comment]
Indeed, I would go with this.

**Comment by be1** [comment]
Thanks for merging!

**Pull request merged**
